// Re-export all types from @ehr/shared as the single source of truth
export type {
  UserRole,
  User,
  Patient,
  CreatePatientInput,
  EncounterStatus,
  Encounter,
  CreateEncounterInput,
  AllergySeverity,
  Allergy,
  Document,
  ProcedureTemplate,
  ProcedureTemplateWithContent,
  AppointmentStatus,
  Appointment,
  AppointmentType,
  CreateAppointmentInput,
  OcrProcessingStatus,
  OcrDocumentType,
  OcrFieldStatus,
  OcrResult,
  OcrFieldMapping,
  ReferralUploadResult,
  PendingReferral,
  ReferralDetail,
  CalendarEvent,
  CreateCalendarEventInput,
  OnCallPeriod,
  CreateOnCallPeriodInput,
  PatientTask,
  CreateTaskInput,
  LoginRequest,
  LoginResponse,
  ApiError,
} from '@ehr/shared';
